import * as pulumi from "@pulumi/pulumi";
import * as gandi from "@pulumiverse/gandi";

export const powerd6orgDomain = new gandi.domains.Domain("powerd6orgDomain", {
    admin: {
        city: "Malpica de Bergantiños",
        country: "ES",
        dataObfuscated: true,
        email: "hector.zacharias@gmail.com",
        extraParameters: {
            birth_city: "",
            birth_country: "",
            birth_date: "",
            birth_department: "",
        },
        familyName: "Castelli Zacharias",
        givenName: "Héctor",
        mailObfuscated: true,
        phone: "+34.677059383",
        state: "ES-C",
        streetAddr: "Rua Canido 57",
        type: "person",
        zip: "15113",
    },
    billing: {
        city: "Malpica de Bergantiños",
        country: "ES",
        dataObfuscated: true,
        email: "hector.zacharias@gmail.com",
        extraParameters: {
            birth_city: "",
            birth_country: "",
            birth_date: "",
            birth_department: "",
        },
        familyName: "Castelli Zacharias",
        givenName: "Héctor",
        mailObfuscated: true,
        phone: "+34.677059383",
        state: "ES-C",
        streetAddr: "Rua Canido 57",
        type: "person",
        zip: "15113",
    },
    name: "powerd6.org",
    owner: {
        city: "Malpica de Bergantiños",
        country: "ES",
        dataObfuscated: true,
        email: "hector.zacharias@gmail.com",
        extraParameters: {
            birth_city: "",
            birth_country: "",
            birth_date: "",
            birth_department: "",
        },
        familyName: "Castelli Zacharias",
        givenName: "Héctor",
        mailObfuscated: true,
        phone: "+34.677059383",
        state: "ES-C",
        streetAddr: "Rua Canido 57",
        type: "person",
        zip: "15113",
    },
    tech: {
        city: "Malpica de Bergantiños",
        country: "ES",
        dataObfuscated: true,
        email: "hector.zacharias@gmail.com",
        extraParameters: {
            birth_city: "",
            birth_country: "",
            birth_date: "",
            birth_department: "",
        },
        familyName: "Castelli Zacharias",
        givenName: "Héctor",
        mailObfuscated: true,
        phone: "+34.677059383",
        state: "ES-C",
        streetAddr: "Rua Canido 57",
        type: "person",
        zip: "15113",
    },
}, {
    protect: true,
});
