name: Continuous Intregration (Astro)
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - name: Build website
        run: |-
          npm run build
      - name: Upload website
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: dist/
          if-no-files-found: error