name: Continuous Integration (mdBook)
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install mdbook and plugins
        run: |-
          cargo install mdbook || true
          cargo install mdbook-linkcheck || true
          cargo install mdbook-footnote || true
          cargo install mdbook-toc || true
      - name: Build mdbook
        run: |-
          mdbook build
      - name: Upload book
        uses: actions/upload-artifact@v3
        with:
          name: book
          path: book/
          if-no-files-found: error