name: Continuous Integration (Infrastructure)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'infra/*'
      - '.github/workflows/pulumi-ci.yml'


env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_STACK_NAME: powerd6/powerd6/live
  PULUMI_WORKING_DIRECTORY: infra

jobs:
  pulumi:
    name: Pulumi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - run: npm ci
        working-directory: ${{ env.PULUMI_WORKING_DIRECTORY }}
      - name: PR previews
        if: ${{ github.event_name == 'pull_request' }}
        uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: ${{ env.PULUMI_STACK_NAME }}
          work-dir: ${{ env.PULUMI_WORKING_DIRECTORY }}
          comment-on-pr: true
      - name: Apply infrastructure update
        if: ${{ github.event_name == 'push' }}
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: ${{ env.PULUMI_STACK_NAME }}
          work-dir: ${{ env.PULUMI_WORKING_DIRECTORY }}