name: Sync Repository Settings

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Label Syncer
        uses: micnncim/action-label-syncer@v1.3.0
        with:
          repository: |
            powerd6/.github
            powerd6/core-rules
            powerd6/specification
            powerd6/landing-page
            powerd6/tools
          token: ${{ secrets.ORG_ADMIN_TOKEN }}
