name: Set Default Labels

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  set-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Label Syncer
        uses: micnncim/action-label-syncer@v1.3.0
        with:
          repository: |
              power-d6/.github
            # Add new repositories here!
          token: ${{ secrets.ORG_ADMIN_TOKEN }}
